# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme


# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
rtl                      : # true, false (default) # turns direction of the page into right to left for RTL languages
title                    : "swiyu technical documentation"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Fachbereich e-ID"
description              : "Documentation of the technical architecture, components, and implementations for swiyu - the Swiss e-ID Trust Infrastructure"
url                      : "https://swiyu-admin-ch.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "selinare.github.io/swiyu-admin-ch"
teaser                   : "/assets/images/swiyu_logo_name.jpeg"
logo                     : "/assets/images/swiyu_logo_88_88.jpg"
masthead_title           : swiyu
breadcrumbs              : true #, false (default)
words_per_minute         : 200
enable_copy_code_button  : true #, false (default)
copyright                : "Swiss Confederation" 
copyright_url            : https://www.eid.admin.ch/en/rechtliches-e
comments:
  provider               : false #(default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false
search                   : true #, false (default)
search_full_content      : true #, false (default)
search_provider          : # lunr (default), algolia, google
lunr:
  search_within_pages    : true
  search_full_content    : true
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related - none
# Social Sharing - none
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics - none

# Site Author
author:
  name             : "Your Name"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Feedback and Contributions"
      icon: "fab fa-fw fa-github"
      url: https://github.com/swiyu-admin-ch/swiyu-admin-ch.github.io
    - label: "Release Announcements"
      url: /release-announcements/
    - label: "Community"
      icon: "fab fa-fw fa-github"
      url: https://github.com/swiyu-admin-ch/community

# Reading Files
include:
  - .htaccess
  - _pages
  - _cookbooks
  - _specifications
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Europe/Zurich


# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Collection as an overview for the Cookbooks and Specifications
collections:
  cookbooks:
    output: true
    permalink: /:collection/:path/
    order:
      - onboarding-base-and-trust-registry.md
      - onboarding-generic-verifier.md
      - onboarding-generic-issuer.md
      - how-to-use-beta-id.md
      - vc-visual-presentation.md
  specifications:
    output: true
    permalink: /:collection/:path/
    order:
      - interoperability-profile.md
      - trust-protocol.md
      - oca.md
           
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false #true
      read_time: true
      comments: # true
      share: false #true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false #true

  #  _cookbooks
  - scope:
      path: ""
      type: cookbooks
    values:
      layout: single
      author_profile: false
      share: false  
      sidebar:
        nav: "cookbooks_sidebarmenu"

    #  _specifications
  - scope:
      path: ""
      type: specifications
    values:
      layout: single
      author_profile: false
      share: false  
      sidebar:
        nav: "specifications_sidebarmenu"
      
